// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRequestLog = "request_log"

// RequestLog mapped from table <request_log>
type RequestLog struct {
	ID                   int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`
	RequestID            string    `gorm:"column:request_id;not null;uniqueIndex:uk_request_id;comment:请求唯一标识(UUID)" json:"request_id"`
	RequestType          string    `gorm:"column:request_type;not null;index:idx_request_type;comment:请求类型: ai_chat/transfer_op/command_op/human_chat" json:"request_type"`
	UserID               string    `gorm:"column:user_id;not null;index:idx_user_id;comment:用户ID" json:"user_id"`
	UserType             string    `gorm:"column:user_type;not null;default:customer;comment:用户类型: wecom/customer" json:"user_type"`
	AgentID              int64     `gorm:"column:agent_id;not null;default:0;index:idx_agent_id;comment:应用ID" json:"agent_id"`
	Channel              string    `gorm:"column:channel;not null;default:'';index:idx_channel;comment:AI渠道" json:"channel"`
	ModelName            string    `gorm:"column:model_name;not null;default:'';comment:模型名称" json:"model_name"`
	ReqContent           string    `gorm:"column:req_content;not null;comment:用户发送内容" json:"req_content"`
	ReqContentLength     int       `gorm:"column:req_content_length;not null;default:0;comment:请求内容长度" json:"req_content_length"`
	IsVoice              bool      `gorm:"column:is_voice;not null;default:false;comment:是否为语音请求" json:"is_voice"`
	ResContent           string    `gorm:"column:res_content;not null;comment:AI响应内容" json:"res_content"`
	ResContentLength     int       `gorm:"column:res_content_length;not null;default:0;comment:响应内容长度" json:"res_content_length"`
	Status               string    `gorm:"column:status;not null;default:success;index:idx_status;comment:处理状态: success/failed/timeout" json:"status"`
	ErrorMsg             string    `gorm:"column:error_msg;comment:错误信息" json:"error_msg"`
	LatencyMs            int       `gorm:"column:latency_ms;not null;default:0;comment:完整响应耗时(毫秒)" json:"latency_ms"`
	FirstPacketLatencyMs int       `gorm:"column:first_packet_latency_ms;not null;default:0;comment:收到模型首个响应包耗时(毫秒)" json:"first_packet_latency_ms"`
	PromptTokens         int       `gorm:"column:prompt_tokens;not null;default:0;comment:消耗prompt token数" json:"prompt_tokens"`
	CompletionTokens     int       `gorm:"column:completion_tokens;not null;default:0;comment:消耗completion token数" json:"completion_tokens"`
	TotalTokens          int       `gorm:"column:total_tokens;not null;default:0;comment:总消耗token数" json:"total_tokens"`
	ConversationID       string    `gorm:"column:conversation_id;not null;default:'';comment:会话ID" json:"conversation_id"`
	TransferID           string    `gorm:"column:transfer_id;not null;default:'';comment:关联转人工ID" json:"transfer_id"`
	CreatedAt            time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;index:idx_created_at;comment:创建时间" json:"created_at"`
	UpdatedAt            time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`
}

// TableName RequestLog's table name
func (*RequestLog) TableName() string {
	return TableNameRequestLog
}
