// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransferLog = "transfer_log"

// TransferLog mapped from table <transfer_log>
type TransferLog struct {
	ID                 int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`
	TransferID         string     `gorm:"column:transfer_id;not null;uniqueIndex:uk_transfer_id;comment:转人工唯一标识(UUID)" json:"transfer_id"`
	UserID             string     `gorm:"column:user_id;not null;index:idx_user_id;comment:用户ID" json:"user_id"`
	UserType           string     `gorm:"column:user_type;not null;default:customer;comment:用户类型: wecom/customer" json:"user_type"`
	AgentID            int64      `gorm:"column:agent_id;not null;default:0;index:idx_agent_id;comment:应用ID" json:"agent_id"`
	OpenKfID           string     `gorm:"column:open_kf_id;not null;default:'';index:idx_open_kf_id;comment:客服ID" json:"open_kf_id"`
	RequestID          string     `gorm:"column:request_id;not null;default:'';index:idx_request_id;comment:关联请求ID" json:"request_id"`
	TransferReason     string     `gorm:"column:transfer_reason;not null;default:'';comment:转人工原因" json:"transfer_reason"`
	UserMessage        string     `gorm:"column:user_message;not null;comment:用户触发转人工的消息内容" json:"user_message"`
	ServiceState       int32      `gorm:"column:service_state;not null;default:2;comment:服务状态: 0-未处理 1-AI接待 2-排队中 3-人工接待" json:"service_state"`
	AssignedServicerID string     `gorm:"column:assigned_servicer_id;not null;default:'';comment:分配的接待人员ID" json:"assigned_servicer_id"`
	AssignmentType     string     `gorm:"column:assignment_type;not null;default:round_robin;comment:分配方式: round_robin/direct/fallback" json:"assignment_type"`
	WasInWorkingHours  bool       `gorm:"column:was_in_working_hours;not null;default:true;comment:是否在工作时间内" json:"was_in_working_hours"`
	TransferStatus     string     `gorm:"column:transfer_status;not null;default:pending;index:idx_transfer_status;comment:转人工状态: pending/accepted/timeout/cancelled" json:"transfer_status"`
	AcceptedAt         *time.Time `gorm:"column:accepted_at;comment:客服接受时间" json:"accepted_at"`
	WaitDurationMs     int32      `gorm:"column:wait_duration_ms;not null;default:0;comment:排队等待时长(毫秒)" json:"wait_duration_ms"`
	SessionEndAt       *time.Time `gorm:"column:session_end_at;comment:会话结束时间" json:"session_end_at"`
	SessionDurationMs  int32      `gorm:"column:session_duration_ms;not null;default:0;comment:会话总时长(毫秒)" json:"session_duration_ms"`
	TransferSuccess    bool       `gorm:"column:transfer_success;not null;default:false;comment:转人工是否成功" json:"transfer_success"`
	ErrorMsg           string     `gorm:"column:error_msg;comment:错误信息" json:"error_msg"`
	WebhookNotified    bool       `gorm:"column:webhook_notified;not null;default:false;comment:是否已发送webhook通知" json:"webhook_notified"`
	CreatedAt          time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;index:idx_created_at;comment:创建时间" json:"created_at"`
	UpdatedAt          time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`
}

// TableName TransferLog's table name
func (*TransferLog) TableName() string {
	return TableNameTransferLog
}
